const IMAGESNUMBER = 78;

const PARTICIPANTSTITLES = [
    "Story Sprinklers",
    "Plot Twisters",
    "Fable Fabricators",
    "Whimsy Weavers",
    "Chaos Creators",
    "Scene Shifters",
    "Adventure Architects",
    "Tale Tinkerers",
    "Legend Builders",
    "Imagination Engineers",
    "Narrative Navigators",
    "Fantasy Forgers",
    "Verse Venturers",
    "Dream Draftsmen",
    "Chronicle Crafters",
    "Epic Embellishers",
    "Mystery Makers",
    "Saga Spinners",
    "Jest Jesters",
    "Odyssey Orchestrators",
];

const PARTICIPANTSACTIONS = [
    "spinning the tale…",
    "weaving the next twist…",
    "conjuring the next chapter…",
    "stirring up the story…",
    "crafting some mischief…",
    "setting the stage…",
    "brewing up the next scene…",
    "igniting the adventure…",
    "bending the plot…",
    "steering the journey…",
    "sparking a new twist…",
    "hatching the next surprise…",
    "shaping the saga…",
    "engineering the excitement…",
    "molding the mystery…",
    "painting the next scene…",
    "mapping the journey…",
    "dancing with destiny…",
    "inventing a turn…",
    "sowing seeds of suspense…",
]